/**
 * Per-page Markdown mirrors.
 *
 * For every public HTML page (item detail, category, tag, collection,
 * comparison, static page) we expose a parallel `.md` URL that returns
 * the same substantive content as a clean Markdown document. AI agents
 * (ChatGPT, Claude, Perplexity, etc.) can consume the `.md` mirror
 * directly without parsing HTML, stripping nav/footer chrome, or
 * dealing with client-side rendered pieces.
 *
 * The HTML page advertises its mirror via:
 *   <link rel="alternate" type="text/markdown" href="/items/foo.md" />
 *
 * Each function in this module renders one page type to a Markdown
 * string. The functions are pure: they take a normalized data object
 * plus the absolute base URL of the site, and return text. No I/O.
 */

import type { ItemData } from '@/lib/content';
import type { Collection } from '@/types/collection';
import type { ComparisonData } from '@/types/comparison';

type Comparison = ComparisonData;

/** Strip a trailing slash from the base URL so we can `${base}/path`. */
function trimBase(base: string): string {
	return base.replace(/\/+$/, '');
}

/** Render a category reference (string or `{name,id}`) to its display name. */
function categoryName(cat: ItemData['category']): string {
	if (Array.isArray(cat)) {
		return cat
			.map((c) => (typeof c === 'string' ? c : c?.name ?? c?.id ?? ''))
			.filter(Boolean)
			.join(', ');
	}
	if (!cat) return '';
	return typeof cat === 'string' ? cat : cat.name ?? cat.id ?? '';
}

/** Render a list of tags (strings or `{name,id}`) to comma-joined names. */
function tagNames(tags: ItemData['tags']): string[] {
	if (!tags) return [];
	return tags
		.map((t) => (typeof t === 'string' ? t : (t?.name ?? t?.id ?? '')))
		.filter((s): s is string => Boolean(s));
}

/**
 * Render a single directory item to Markdown.
 *
 * Includes the item's name, description, structured metadata
 * (URL, category, tags, etc.), and the full body markdown if present.
 * The trailing footer reminds agents where the canonical version lives.
 */
export function renderItemMarkdown(
	item: { meta: ItemData; content?: string },
	options: { baseUrl: string; locale?: string }
): string {
	const base = trimBase(options.baseUrl);
	const localePrefix = options.locale && options.locale !== 'en' ? `/${options.locale}` : '';
	const canonicalUrl = `${base}${localePrefix}/items/${item.meta.slug}`;

	const lines: string[] = [];
	lines.push(`# ${item.meta.name}`);
	lines.push('');
	if (item.meta.description) {
		lines.push(`> ${item.meta.description.replace(/\n+/g, ' ')}`);
		lines.push('');
	}

	const facts: string[] = [];
	if (item.meta.source_url) facts.push(`- **URL:** ${item.meta.source_url}`);
	const cat = categoryName(item.meta.category);
	if (cat) facts.push(`- **Category:** ${cat}`);
	const tags = tagNames(item.meta.tags);
	if (tags.length > 0) facts.push(`- **Tags:** ${tags.join(', ')}`);
	if (item.meta.featured) facts.push(`- **Featured:** yes`);
	if (item.meta.publisher) facts.push(`- **Publisher:** ${item.meta.publisher}`);
	if (item.meta.updated_at) facts.push(`- **Updated:** ${item.meta.updated_at}`);
	facts.push(`- **Canonical page:** ${canonicalUrl}`);
	lines.push(...facts);
	lines.push('');

	const body = (item.content ?? item.meta.markdown ?? '').trim();
	if (body) {
		lines.push('## Details');
		lines.push('');
		lines.push(body);
		lines.push('');
	}

	lines.push('---');
	lines.push('');
	lines.push(`_This Markdown mirror is generated by Ever Works for AI agents. The canonical HTML page is at ${canonicalUrl}._`);
	lines.push('');

	return lines.join('\n');
}

/**
 * Render a category page (the items in that category) to Markdown.
 * Used for /categories/<id>.md.
 */
export function renderCategoryMarkdown(
	category: { id: string; name: string; description?: string } | undefined,
	items: ItemData[],
	options: { baseUrl: string; locale?: string; categoryRef: string }
): string {
	const base = trimBase(options.baseUrl);
	const localePrefix = options.locale && options.locale !== 'en' ? `/${options.locale}` : '';
	const canonicalUrl = `${base}${localePrefix}/categories/${options.categoryRef}`;
	const name = category?.name ?? options.categoryRef;

	const lines: string[] = [];
	lines.push(`# ${name}`);
	lines.push('');
	lines.push(`> Browse ${items.length} ${items.length === 1 ? 'item' : 'items'} in ${name}.`);
	lines.push('');
	if (category?.description) {
		lines.push(category.description);
		lines.push('');
	}

	if (items.length > 0) {
		lines.push('## Items');
		lines.push('');
		for (const item of items) {
			const url = `${base}${localePrefix}/items/${item.slug}`;
			const desc = (item.description ?? '').replace(/\n+/g, ' ');
			lines.push(`- [${item.name}](${url})${desc ? ` — ${desc}` : ''}`);
		}
		lines.push('');
	}

	lines.push('---');
	lines.push('');
	lines.push(`_Canonical page: ${canonicalUrl}_`);
	lines.push('');
	return lines.join('\n');
}

/** Render a tag page (items with that tag) to Markdown. */
export function renderTagMarkdown(
	tag: { id: string; name: string } | undefined,
	items: ItemData[],
	options: { baseUrl: string; locale?: string; tagRef: string }
): string {
	const base = trimBase(options.baseUrl);
	const localePrefix = options.locale && options.locale !== 'en' ? `/${options.locale}` : '';
	const canonicalUrl = `${base}${localePrefix}/tags/${options.tagRef}`;
	const name = tag?.name ?? options.tagRef;

	const lines: string[] = [];
	lines.push(`# ${name}`);
	lines.push('');
	lines.push(`> Browse ${items.length} ${items.length === 1 ? 'item' : 'items'} tagged with ${name}.`);
	lines.push('');

	if (items.length > 0) {
		lines.push('## Items');
		lines.push('');
		for (const item of items) {
			const url = `${base}${localePrefix}/items/${item.slug}`;
			const desc = (item.description ?? '').replace(/\n+/g, ' ');
			lines.push(`- [${item.name}](${url})${desc ? ` — ${desc}` : ''}`);
		}
		lines.push('');
	}

	lines.push('---');
	lines.push('');
	lines.push(`_Canonical page: ${canonicalUrl}_`);
	lines.push('');
	return lines.join('\n');
}

/** Render a curated collection page to Markdown. */
export function renderCollectionMarkdown(
	collection: Collection,
	items: ItemData[],
	options: { baseUrl: string; locale?: string }
): string {
	const base = trimBase(options.baseUrl);
	const localePrefix = options.locale && options.locale !== 'en' ? `/${options.locale}` : '';
	const slug = collection.slug || collection.id;
	const canonicalUrl = `${base}${localePrefix}/collections/${slug}`;

	const lines: string[] = [];
	lines.push(`# ${collection.name}`);
	lines.push('');
	if (collection.description) {
		lines.push(`> ${collection.description.replace(/\n+/g, ' ')}`);
		lines.push('');
	}

	if (items.length > 0) {
		lines.push('## Items');
		lines.push('');
		for (const item of items) {
			const url = `${base}${localePrefix}/items/${item.slug}`;
			const desc = (item.description ?? '').replace(/\n+/g, ' ');
			lines.push(`- [${item.name}](${url})${desc ? ` — ${desc}` : ''}`);
		}
		lines.push('');
	}

	lines.push('---');
	lines.push('');
	lines.push(`_Canonical page: ${canonicalUrl}_`);
	lines.push('');
	return lines.join('\n');
}

/** Render a comparison page (two items side-by-side) to Markdown. */
export function renderComparisonMarkdown(
	comparison: Comparison,
	options: { baseUrl: string; locale?: string }
): string {
	const base = trimBase(options.baseUrl);
	const localePrefix = options.locale && options.locale !== 'en' ? `/${options.locale}` : '';
	const canonicalUrl = `${base}${localePrefix}/comparisons/${comparison.slug}`;

	const lines: string[] = [];
	lines.push(`# ${comparison.title}`);
	lines.push('');
	if (comparison.summary) {
		lines.push(`> ${comparison.summary.replace(/\n+/g, ' ')}`);
		lines.push('');
	}

	lines.push('## Compared');
	lines.push('');
	lines.push(`- **${comparison.item_a_name}** — ${base}${localePrefix}/items/${comparison.item_a_slug}`);
	lines.push(`- **${comparison.item_b_name}** — ${base}${localePrefix}/items/${comparison.item_b_slug}`);
	lines.push('');

	if (Array.isArray(comparison.dimensions) && comparison.dimensions.length > 0) {
		lines.push('## Dimensions');
		lines.push('');
		for (const dim of comparison.dimensions) {
			const name = (dim as { name?: string; title?: string }).name ?? (dim as { title?: string }).title ?? '';
			if (name) lines.push(`- ${name}`);
		}
		lines.push('');
	}

	lines.push('---');
	lines.push('');
	lines.push(`_Canonical page: ${canonicalUrl}_`);
	lines.push('');
	return lines.join('\n');
}

/** Render a static page (about/help/etc) to Markdown from its raw content. */
export function renderStaticPageMarkdown(
	pageData: { metadata?: Record<string, unknown>; content?: string } | null,
	options: { title: string; path: string; baseUrl: string; locale?: string; defaultContent?: string }
): string {
	const base = trimBase(options.baseUrl);
	const localePrefix = options.locale && options.locale !== 'en' ? `/${options.locale}` : '';
	const canonicalUrl = `${base}${localePrefix}${options.path}`;

	const title = (pageData?.metadata?.title as string) || options.title;
	const description = (pageData?.metadata?.description as string) || '';
	const lastUpdated = (pageData?.metadata?.lastUpdated as string) || '';

	const body = (pageData?.content ?? options.defaultContent ?? '').trim();

	const lines: string[] = [];
	lines.push(`# ${title}`);
	lines.push('');
	if (description) {
		lines.push(`> ${description.replace(/\n+/g, ' ')}`);
		lines.push('');
	}
	if (lastUpdated) {
		lines.push(`_Last updated: ${lastUpdated}_`);
		lines.push('');
	}
	if (body) {
		lines.push(body);
		lines.push('');
	}
	lines.push('---');
	lines.push('');
	lines.push(`_Canonical page: ${canonicalUrl}_`);
	lines.push('');

	return lines.join('\n');
}

/** Standard headers for `.md` mirror responses. */
export const MARKDOWN_RESPONSE_HEADERS = {
	'Content-Type': 'text/markdown; charset=utf-8',
	'Cache-Control': 'public, max-age=300, s-maxage=900',
	'Access-Control-Allow-Origin': '*',
	'X-Robots-Tag': 'noindex'
} as const;
