apiVersion: v1
kind: Service
metadata:
    name: ${WORK_SLUG}
    namespace: ${NAMESPACE}
    labels:
        ever-works.io/managed: "true"
        ever-works.io/work-id: "${WORK_ID}"
        app.kubernetes.io/name: ${WORK_SLUG}
        app.kubernetes.io/managed-by: ever-works-k8s-plugin
spec:
    type: ClusterIP
    selector:
        app.kubernetes.io/name: ${WORK_SLUG}
    ports:
        - name: http
          port: 80
          targetPort: 3000
          protocol: TCP
