import { test, expect } from '@playwright/test';

/**
 * Smoke coverage for the public SEO / manifest surface generated by
 * `apps/web/app/{robots,sitemap,opengraph-image}.{ts,tsx}` and the
 * public favicon.
 *
 * These endpoints are public, statically generated (or cached), and
 * must always return a successful, non-server-error response — they
 * are the first thing crawlers and link-preview bots hit. The contract
 * here is intentionally conservative: status < 500 plus a sanity check
 * on the response content-type / body shape so a regression that
 * silently drops the file is caught.
 */
test.describe('Public: SEO manifest surface', () => {
	test('GET /robots.txt is served', async ({ request }) => {
		const response = await request.get('/robots.txt');

		expect(response.status()).toBeLessThan(500);
		// Next's metadata router serves robots from the App Router; on a
		// healthy build it is always a 200 with a text/plain payload that
		// at minimum names the user-agent rule.
		if (response.status() === 200) {
			const body = await response.text();
			expect(body.toLowerCase()).toContain('user-agent');
		}
	});

	test('GET /sitemap.xml is served', async ({ request }) => {
		// Sitemap generation reads from the Git CMS and may return 200 with
		// an XML body, or — if the content repo is not yet cloned — fall
		// back to a 4xx. Both are acceptable; a 5xx is a regression.
		const response = await request.get('/sitemap.xml');

		expect(response.status()).toBeLessThan(500);
		if (response.status() === 200) {
			const body = await response.text();
			expect(body.trim().startsWith('<?xml')).toBeTruthy();
		}
	});

	test('GET /opengraph-image returns a non-server-error response', async ({ request }) => {
		const response = await request.get('/opengraph-image', { maxRedirects: 0 });

		expect(response.status()).toBeLessThan(500);
	});

	test('GET /favicon.ico is served', async ({ request }) => {
		const response = await request.get('/favicon.ico', { maxRedirects: 0 });

		expect(response.status()).toBeLessThan(500);
	});
});
