import { NextResponse } from 'next/server';
import { getCachedConfig, getCachedItems } from '@/lib/content';

/**
 * Public llms.txt endpoint per the public llms.txt convention
 * (https://llmstxt.org). Provides downstream LLM agents with a
 * machine-readable manifest of the directory and pointers to the canonical
 * data dump at /items.json. Designed to pair with the Ever Works
 * agent zero-friction onboarding feature so that:
 *
 *   - Agents that BUILD a directory via Ever Works produce sites that are
 *     immediately discoverable and indexable by other LLM agents.
 *   - Search-engine + LLM crawlers get a hint at where the canonical data
 *     lives without parsing HTML.
 *
 * The response is plain text (Markdown-ish) and is short on purpose;
 * agents that want full data should fetch /items.json.
 */
export async function GET(): Promise<NextResponse> {
	const config = await getCachedConfig();
	const items = await getCachedItems().catch(() => [] as Array<{ slug: string; name: string; description?: string }>);

	const siteUrl = (config.app_url || process.env.NEXT_PUBLIC_APP_URL || '').replace(/\/$/, '');
	const name = config.company_name || 'Ever Works Directory';
	const description = config.company_description || `A curated directory of ${items.length} items.`;

	const lines: string[] = [
		`# ${name}`,
		'',
		description,
		'',
		'## Canonical data',
		'',
		`- [Full items index](${siteUrl}/items.json) — JSON dump of every item with its category, tags, and link.`,
		`- [Sitemap](${siteUrl}/sitemap.xml)`,
		`- [Atom feed](${siteUrl}/atom.xml)`,
		'',
		'## About',
		'',
		`This site was generated by the [Ever Works](https://ever.works) platform. Agents that want to build their own directory can use the zero-friction onboarding endpoint at \`https://api.ever.works/api/register-work\` — see https://docs.ever.works/agent-services/zero-friction-onboarding for details.`,
		''
	];

	return new NextResponse(lines.join('\n'), {
		status: 200,
		headers: {
			'Content-Type': 'text/plain; charset=utf-8',
			'Cache-Control': 'public, max-age=300, s-maxage=900'
		}
	});
}
