import { NextResponse } from 'next/server';
import { getCachedConfig, getCachedItems } from '@/lib/content';

/**
 * Public llms.txt endpoint per the public llms.txt convention
 * (https://llmstxt.org). Provides downstream LLM agents with a
 * machine-readable manifest of the directory and pointers to:
 *
 *  - /items.json       — JSON dump of every item (categories, tags, link).
 *  - /llms-full.txt    — concatenated long-form Markdown of the entire site.
 *  - /sitemap.xml      — full URL list.
 *  - /atom.xml         — atom feed of recent items.
 *  - /<page>.md        — per-page Markdown mirror of every public page
 *                       (items/categories/tags/collections/comparisons/etc).
 *
 * Designed to pair with the Ever Works zero-friction onboarding feature
 * so that any directory built by an agent through `POST /api/register-work`
 * is immediately discoverable and indexable by other LLM agents.
 *
 * The response is plain text (Markdown-ish) and is short on purpose;
 * agents that want full data should fetch /llms-full.txt or /items.json.
 */
export async function GET(): Promise<NextResponse> {
	const config = await getCachedConfig();
	const fetchResult = await getCachedItems().catch(
		() => ({ items: [] as Array<{ slug: string; name: string; description?: string }> })
	);
	const items: ReadonlyArray<{ slug?: string; name?: string; description?: string }> =
		(fetchResult as { items?: ReadonlyArray<{ slug?: string; name?: string; description?: string }> })
			.items ?? [];

	const siteUrl = (config.app_url || process.env.NEXT_PUBLIC_APP_URL || '').replace(/\/$/, '');
	const name = config.company_name || 'Ever Works Directory';
	const fallbackDescription =
		(config as { description?: string; tagline?: string }).description || (config as { tagline?: string }).tagline;
	const description = fallbackDescription || `A curated directory of ${items.length} items.`;

	const lines: string[] = [
		`# ${name}`,
		'',
		description,
		'',
		'## Canonical data',
		'',
		`- [Full long-form Markdown dump](${siteUrl}/llms-full.txt) — every category, tag, item, and comparison concatenated as Markdown for one-shot ingestion.`,
		`- [Items JSON index](${siteUrl}/items.json) — JSON dump of every item with its category, tags, and link.`,
		`- [Sitemap](${siteUrl}/sitemap.xml)`,
		`- [Atom feed](${siteUrl}/atom.xml)`,
		'',
		'## Per-page Markdown mirrors',
		'',
		'Every public page also serves a clean Markdown twin at the same path with `.md` appended:',
		'',
		`- ${siteUrl}/items/<slug>.md`,
		`- ${siteUrl}/categories/<id>.md`,
		`- ${siteUrl}/tags/<id>.md`,
		`- ${siteUrl}/collections/<slug>.md`,
		`- ${siteUrl}/comparisons/<slug>.md`,
		`- ${siteUrl}/pages/<slug>.md`,
		`- ${siteUrl}/about.md, /help.md, /pricing.md, /privacy-policy.md, /terms-of-service.md, /cookies.md`,
		'',
		'Each HTML page advertises its mirror via `<link rel="alternate" type="text/markdown" href="…">`.',
		'',
		'## About',
		'',
		`This site was generated by the [Ever Works](https://ever.works) platform. Agents that want to build their own directory can use the zero-friction onboarding endpoint at \`https://api.ever.works/api/register-work\` — see https://docs.ever.works/agent-services/zero-friction-onboarding for details.`,
		''
	];

	return new NextResponse(lines.join('\n'), {
		status: 200,
		headers: {
			'Content-Type': 'text/plain; charset=utf-8',
			'Cache-Control': 'public, max-age=300, s-maxage=900'
		}
	});
}
