CREATE INDEX "accounts_tenant_id_idx" ON "accounts" USING btree ("tenant_id");--> statement-breakpoint
CREATE INDEX "activity_logs_tenant_id_idx" ON "activityLogs" USING btree ("tenant_id");--> statement-breakpoint
CREATE INDEX "authenticators_tenant_id_idx" ON "authenticators" USING btree ("tenant_id");--> statement-breakpoint
CREATE INDEX "client_profile_tenant_id_idx" ON "client_profiles" USING btree ("tenant_id");--> statement-breakpoint
CREATE INDEX "comments_tenant_id_idx" ON "comments" USING btree ("tenant_id");--> statement-breakpoint
CREATE INDEX "companies_tenant_id_idx" ON "companies" USING btree ("tenant_id");--> statement-breakpoint
CREATE INDEX "favorites_tenant_id_idx" ON "favorites" USING btree ("tenant_id");--> statement-breakpoint
CREATE INDEX "featured_items_tenant_id_idx" ON "featured_items" USING btree ("tenant_id");--> statement-breakpoint
CREATE INDEX "integration_mappings_tenant_id_idx" ON "integration_mappings" USING btree ("tenant_id");--> statement-breakpoint
CREATE INDEX "item_audit_logs_tenant_id_idx" ON "item_audit_logs" USING btree ("tenant_id");--> statement-breakpoint
CREATE INDEX "item_location_index_tenant_id_idx" ON "item_location_index" USING btree ("tenant_id");--> statement-breakpoint
CREATE INDEX "item_views_tenant_id_idx" ON "item_views" USING btree ("tenant_id");--> statement-breakpoint
CREATE INDEX "items_companies_tenant_id_idx" ON "items_companies" USING btree ("tenant_id");--> statement-breakpoint
CREATE INDEX "location_index_meta_tenant_id_idx" ON "location_index_meta" USING btree ("tenant_id");--> statement-breakpoint
CREATE INDEX "moderation_history_tenant_id_idx" ON "moderation_history" USING btree ("tenant_id");--> statement-breakpoint
CREATE INDEX "newsletter_subscriptions_tenant_id_idx" ON "newsletterSubscriptions" USING btree ("tenant_id");--> statement-breakpoint
CREATE INDEX "notifications_tenant_id_idx" ON "notifications" USING btree ("tenant_id");--> statement-breakpoint
CREATE INDEX "password_reset_tokens_tenant_id_idx" ON "passwordResetTokens" USING btree ("tenant_id");--> statement-breakpoint
CREATE INDEX "payment_accounts_tenant_id_idx" ON "paymentAccounts" USING btree ("tenant_id");--> statement-breakpoint
CREATE INDEX "payment_providers_tenant_id_idx" ON "paymentProviders" USING btree ("tenant_id");--> statement-breakpoint
CREATE INDEX "permissions_tenant_id_idx" ON "permissions" USING btree ("tenant_id");--> statement-breakpoint
CREATE INDEX "reports_tenant_id_idx" ON "reports" USING btree ("tenant_id");--> statement-breakpoint
CREATE INDEX "role_permissions_tenant_id_idx" ON "role_permissions" USING btree ("tenant_id");--> statement-breakpoint
CREATE INDEX "roles_tenant_id_idx" ON "roles" USING btree ("tenant_id");--> statement-breakpoint
CREATE INDEX "seed_status_tenant_id_idx" ON "seed_status" USING btree ("tenant_id");--> statement-breakpoint
CREATE INDEX "sponsor_ads_tenant_id_idx" ON "sponsor_ads" USING btree ("tenant_id");--> statement-breakpoint
CREATE INDEX "subscription_history_tenant_id_idx" ON "subscriptionHistory" USING btree ("tenant_id");--> statement-breakpoint
CREATE INDEX "subscriptions_tenant_id_idx" ON "subscriptions" USING btree ("tenant_id");--> statement-breakpoint
CREATE INDEX "survey_responses_tenant_id_idx" ON "survey_responses" USING btree ("tenant_id");--> statement-breakpoint
CREATE INDEX "surveys_tenant_id_idx" ON "surveys" USING btree ("tenant_id");--> statement-breakpoint
CREATE INDEX "twenty_crm_config_tenant_id_idx" ON "twenty_crm_config" USING btree ("tenant_id");--> statement-breakpoint
CREATE INDEX "user_roles_tenant_id_idx" ON "user_roles" USING btree ("tenant_id");--> statement-breakpoint
CREATE INDEX "users_tenant_id_idx" ON "users" USING btree ("tenant_id");--> statement-breakpoint
CREATE INDEX "votes_tenant_id_idx" ON "votes" USING btree ("tenant_id");