/**
 * Curated dataset of ~300 popular emojis with searchable names and keywords.
 *
 * Inline rather than pulled from a package so the picker stays under
 * the bundle budget (see spec 018 performance-budget) and so we ship
 * zero new dependencies (CLAUDE.md §2).
 */

export interface EmojiEntry {
	/** The literal Unicode emoji character. */
	char: string;
	/** Primary short name without colons, used as the `:rocket` token. */
	name: string;
	/** Extra searchable keywords (lowercase). */
	keywords: readonly string[];
}

export const EMOJI_DATA: readonly EmojiEntry[] = [
	// Smileys & emotion
	{ char: "😀", name: "grinning", keywords: ["happy", "smile", "face"] },
	{ char: "😃", name: "smiley", keywords: ["happy", "joy", "face"] },
	{ char: "😄", name: "smile", keywords: ["happy", "joy"] },
	{ char: "😁", name: "grin", keywords: ["happy", "smile"] },
	{ char: "😆", name: "laughing", keywords: ["happy", "lol"] },
	{ char: "😅", name: "sweat_smile", keywords: ["nervous", "smile"] },
	{ char: "🤣", name: "rofl", keywords: ["lol", "rolling", "laugh"] },
	{ char: "😂", name: "joy", keywords: ["lol", "cry", "tears"] },
	{ char: "🙂", name: "slight_smile", keywords: ["smile"] },
	{ char: "🙃", name: "upside_down", keywords: ["sarcasm", "smile"] },
	{ char: "😉", name: "wink", keywords: ["flirt"] },
	{ char: "😊", name: "blush", keywords: ["happy", "shy"] },
	{ char: "😇", name: "innocent", keywords: ["angel", "halo"] },
	{ char: "🥰", name: "smiling_face_hearts", keywords: ["love", "hearts"] },
	{ char: "😍", name: "heart_eyes", keywords: ["love", "crush"] },
	{ char: "🤩", name: "star_struck", keywords: ["star", "eyes", "excited"] },
	{ char: "😘", name: "kissing_heart", keywords: ["love", "kiss"] },
	{ char: "😗", name: "kissing", keywords: ["kiss"] },
	{ char: "😚", name: "kissing_closed_eyes", keywords: ["kiss"] },
	{ char: "🥲", name: "smiling_tear", keywords: ["happy", "cry"] },
	{ char: "😋", name: "yum", keywords: ["tongue", "delicious"] },
	{ char: "😜", name: "stuck_out_tongue_wink", keywords: ["joke", "tongue"] },
	{ char: "🤪", name: "zany", keywords: ["crazy", "silly"] },
	{ char: "🤔", name: "thinking", keywords: ["hmm", "ponder"] },
	{ char: "🤨", name: "raised_eyebrow", keywords: ["skeptical"] },
	{ char: "😐", name: "neutral", keywords: ["meh"] },
	{ char: "😑", name: "expressionless", keywords: ["blank"] },
	{ char: "😶", name: "no_mouth", keywords: ["silent"] },
	{ char: "🙄", name: "rolling_eyes", keywords: ["annoyed"] },
	{ char: "😏", name: "smirk", keywords: ["smug"] },
	{ char: "😬", name: "grimacing", keywords: ["awkward"] },
	{ char: "😴", name: "sleeping", keywords: ["zzz", "sleep"] },
	{ char: "😪", name: "sleepy", keywords: ["tired"] },
	{ char: "🤤", name: "drooling", keywords: ["hungry"] },
	{ char: "😎", name: "sunglasses", keywords: ["cool"] },
	{ char: "🤓", name: "nerd", keywords: ["geek", "glasses"] },
	{ char: "🥳", name: "partying", keywords: ["party", "celebrate", "hat"] },
	{ char: "🤗", name: "hugs", keywords: ["hug"] },
	{ char: "🤭", name: "hand_over_mouth", keywords: ["oops", "giggle"] },
	{ char: "😢", name: "cry", keywords: ["sad", "tear"] },
	{ char: "😭", name: "sob", keywords: ["sad", "cry"] },
	{ char: "😱", name: "scream", keywords: ["shock", "fear"] },
	{ char: "😨", name: "fearful", keywords: ["scared"] },
	{ char: "😰", name: "cold_sweat", keywords: ["anxious"] },
	{ char: "😡", name: "angry", keywords: ["mad", "rage"] },
	{ char: "😤", name: "triumph", keywords: ["frustrated"] },
	{ char: "🤯", name: "exploding_head", keywords: ["mindblown", "shock"] },
	{ char: "💀", name: "skull", keywords: ["dead", "lol"] },
	{ char: "👻", name: "ghost", keywords: ["spooky", "halloween"] },
	{ char: "👽", name: "alien", keywords: ["ufo", "space"] },
	{ char: "🤖", name: "robot", keywords: ["bot", "ai", "android"] },
	{ char: "💩", name: "poop", keywords: ["funny"] },

	// Hand gestures & people
	{ char: "👋", name: "wave", keywords: ["hello", "bye", "hand"] },
	{ char: "🤚", name: "raised_back_hand", keywords: ["stop", "hand"] },
	{ char: "🖐️", name: "raised_hand_fingers_splayed", keywords: ["hand"] },
	{ char: "✋", name: "raised_hand", keywords: ["high_five", "stop"] },
	{ char: "🖖", name: "vulcan", keywords: ["spock", "trek"] },
	{ char: "👌", name: "ok_hand", keywords: ["ok", "perfect"] },
	{ char: "🤌", name: "pinched_fingers", keywords: ["italian"] },
	{ char: "🤏", name: "pinching_hand", keywords: ["small", "tiny"] },
	{ char: "✌️", name: "peace", keywords: ["victory", "v"] },
	{ char: "🤞", name: "crossed_fingers", keywords: ["luck", "hope"] },
	{ char: "🤟", name: "love_you", keywords: ["rock", "love"] },
	{ char: "🤘", name: "metal", keywords: ["rock", "horns"] },
	{ char: "🤙", name: "call_me", keywords: ["shaka", "hang_loose"] },
	{ char: "👈", name: "point_left", keywords: ["arrow", "hand"] },
	{ char: "👉", name: "point_right", keywords: ["arrow", "hand"] },
	{ char: "👆", name: "point_up_2", keywords: ["arrow", "hand"] },
	{ char: "👇", name: "point_down", keywords: ["arrow", "hand"] },
	{ char: "☝️", name: "point_up", keywords: ["finger", "one"] },
	{ char: "👍", name: "thumbs_up", keywords: ["like", "approve", "yes"] },
	{ char: "👎", name: "thumbs_down", keywords: ["dislike", "no"] },
	{ char: "✊", name: "fist_raised", keywords: ["solidarity"] },
	{ char: "👊", name: "fist_bump", keywords: ["punch"] },
	{ char: "🤛", name: "fist_left", keywords: ["punch"] },
	{ char: "🤜", name: "fist_right", keywords: ["punch"] },
	{ char: "👏", name: "clap", keywords: ["applause", "bravo"] },
	{ char: "🙌", name: "raised_hands", keywords: ["celebrate", "praise"] },
	{ char: "👐", name: "open_hands", keywords: ["hug"] },
	{ char: "🤝", name: "handshake", keywords: ["deal", "agreement"] },
	{ char: "🙏", name: "pray", keywords: ["thanks", "please", "namaste"] },
	{ char: "💪", name: "muscle", keywords: ["strong", "biceps"] },
	{ char: "🦾", name: "mechanical_arm", keywords: ["robot", "strong"] },
	{ char: "🧠", name: "brain", keywords: ["mind", "smart"] },
	{ char: "👀", name: "eyes", keywords: ["look", "see", "watch"] },
	{ char: "👶", name: "baby", keywords: ["child", "infant"] },
	{ char: "🧑", name: "person", keywords: ["adult", "human"] },
	{ char: "👨", name: "man", keywords: ["male"] },
	{ char: "👩", name: "woman", keywords: ["female"] },
	{ char: "🧑‍💻", name: "technologist", keywords: ["developer", "coder", "programmer"] },
	{ char: "👨‍💻", name: "man_technologist", keywords: ["developer", "coder"] },
	{ char: "👩‍💻", name: "woman_technologist", keywords: ["developer", "coder"] },
	{ char: "🧑‍🎨", name: "artist", keywords: ["painter", "designer"] },
	{ char: "🧑‍🚀", name: "astronaut", keywords: ["space"] },
	{ char: "🧑‍🔬", name: "scientist", keywords: ["lab"] },
	{ char: "🥷", name: "ninja", keywords: ["stealth"] },

	// Animals & nature
	{ char: "🐶", name: "dog", keywords: ["puppy", "pet"] },
	{ char: "🐱", name: "cat", keywords: ["kitten", "pet"] },
	{ char: "🦊", name: "fox", keywords: ["animal"] },
	{ char: "🐻", name: "bear", keywords: ["animal"] },
	{ char: "🐼", name: "panda", keywords: ["animal", "bear"] },
	{ char: "🐨", name: "koala", keywords: ["animal"] },
	{ char: "🐯", name: "tiger", keywords: ["animal", "big_cat"] },
	{ char: "🦁", name: "lion", keywords: ["animal", "big_cat"] },
	{ char: "🐮", name: "cow", keywords: ["farm", "moo"] },
	{ char: "🐷", name: "pig", keywords: ["farm", "oink"] },
	{ char: "🐸", name: "frog", keywords: ["ribbit"] },
	{ char: "🐵", name: "monkey", keywords: ["primate"] },
	{ char: "🐔", name: "chicken", keywords: ["bird", "farm"] },
	{ char: "🐧", name: "penguin", keywords: ["bird"] },
	{ char: "🐦", name: "bird", keywords: ["tweet"] },
	{ char: "🦆", name: "duck", keywords: ["bird"] },
	{ char: "🦅", name: "eagle", keywords: ["bird"] },
	{ char: "🦉", name: "owl", keywords: ["bird", "wise"] },
	{ char: "🦇", name: "bat", keywords: ["animal", "night"] },
	{ char: "🐺", name: "wolf", keywords: ["animal"] },
	{ char: "🐗", name: "boar", keywords: ["pig", "wild"] },
	{ char: "🐴", name: "horse", keywords: ["animal"] },
	{ char: "🦄", name: "unicorn", keywords: ["magic", "rainbow"] },
	{ char: "🐝", name: "bee", keywords: ["bug", "honey"] },
	{ char: "🐛", name: "bug", keywords: ["caterpillar", "insect"] },
	{ char: "🦋", name: "butterfly", keywords: ["bug", "insect"] },
	{ char: "🐢", name: "turtle", keywords: ["animal", "slow"] },
	{ char: "🐍", name: "snake", keywords: ["reptile"] },
	{ char: "🐙", name: "octopus", keywords: ["sea"] },
	{ char: "🦑", name: "squid", keywords: ["sea"] },
	{ char: "🦐", name: "shrimp", keywords: ["sea", "food"] },
	{ char: "🦀", name: "crab", keywords: ["sea"] },
	{ char: "🐠", name: "fish", keywords: ["sea", "pet"] },
	{ char: "🐳", name: "whale", keywords: ["sea", "ocean"] },
	{ char: "🐬", name: "dolphin", keywords: ["sea"] },
	{ char: "🦈", name: "shark", keywords: ["sea"] },
	{ char: "🦖", name: "trex", keywords: ["dinosaur", "rawr"] },
	{ char: "🦕", name: "sauropod", keywords: ["dinosaur", "longneck"] },
	{ char: "🌸", name: "blossom", keywords: ["flower", "cherry"] },
	{ char: "🌹", name: "rose", keywords: ["flower", "love"] },
	{ char: "🌻", name: "sunflower", keywords: ["flower"] },
	{ char: "🌷", name: "tulip", keywords: ["flower"] },
	{ char: "🌳", name: "tree", keywords: ["nature", "plant"] },
	{ char: "🌲", name: "evergreen", keywords: ["tree", "pine"] },
	{ char: "🌴", name: "palm_tree", keywords: ["tropical"] },
	{ char: "🌵", name: "cactus", keywords: ["desert", "plant"] },
	{ char: "🍀", name: "four_leaf_clover", keywords: ["luck", "shamrock"] },
	{ char: "🍁", name: "maple_leaf", keywords: ["canada", "autumn"] },
	{ char: "🌍", name: "earth_africa", keywords: ["world", "planet"] },
	{ char: "🌎", name: "earth_americas", keywords: ["world", "planet"] },
	{ char: "🌏", name: "earth_asia", keywords: ["world", "planet"] },
	{ char: "🌙", name: "moon", keywords: ["night", "crescent"] },
	{ char: "⭐", name: "star", keywords: ["favorite"] },
	{ char: "🌟", name: "glowing_star", keywords: ["sparkle", "shine"] },
	{ char: "✨", name: "sparkles", keywords: ["shine", "magic"] },
	{ char: "⚡", name: "zap", keywords: ["lightning", "electric"] },
	{ char: "🔥", name: "fire", keywords: ["lit", "hot", "flame"] },
	{ char: "❄️", name: "snowflake", keywords: ["winter", "cold"] },
	{ char: "☀️", name: "sun", keywords: ["sunny", "weather"] },
	{ char: "⛅", name: "partly_sunny", keywords: ["cloudy", "weather"] },
	{ char: "☁️", name: "cloud", keywords: ["weather"] },
	{ char: "🌈", name: "rainbow", keywords: ["pride", "color"] },
	{ char: "💧", name: "droplet", keywords: ["water", "tear"] },
	{ char: "🌊", name: "ocean", keywords: ["wave", "water"] },

	// Food & drink
	{ char: "🍎", name: "apple", keywords: ["fruit", "red"] },
	{ char: "🍊", name: "orange_fruit", keywords: ["fruit"] },
	{ char: "🍋", name: "lemon", keywords: ["fruit", "sour"] },
	{ char: "🍌", name: "banana", keywords: ["fruit"] },
	{ char: "🍉", name: "watermelon", keywords: ["fruit"] },
	{ char: "🍇", name: "grapes", keywords: ["fruit", "wine"] },
	{ char: "🍓", name: "strawberry", keywords: ["fruit", "berry"] },
	{ char: "🥝", name: "kiwi", keywords: ["fruit"] },
	{ char: "🍍", name: "pineapple", keywords: ["fruit"] },
	{ char: "🥑", name: "avocado", keywords: ["fruit"] },
	{ char: "🍅", name: "tomato", keywords: ["fruit", "veggie"] },
	{ char: "🥕", name: "carrot", keywords: ["veggie"] },
	{ char: "🌽", name: "corn", keywords: ["veggie"] },
	{ char: "🌶️", name: "hot_pepper", keywords: ["spicy", "chili"] },
	{ char: "🍞", name: "bread", keywords: ["food"] },
	{ char: "🧀", name: "cheese", keywords: ["food"] },
	{ char: "🍔", name: "hamburger", keywords: ["food", "burger"] },
	{ char: "🍟", name: "fries", keywords: ["food", "potato"] },
	{ char: "🍕", name: "pizza", keywords: ["food"] },
	{ char: "🌭", name: "hot_dog", keywords: ["food"] },
	{ char: "🌮", name: "taco", keywords: ["food", "mexican"] },
	{ char: "🍣", name: "sushi", keywords: ["food", "japanese"] },
	{ char: "🍜", name: "ramen", keywords: ["food", "noodles"] },
	{ char: "🍩", name: "doughnut", keywords: ["food", "donut", "sweet"] },
	{ char: "🍪", name: "cookie", keywords: ["food", "sweet"] },
	{ char: "🍰", name: "cake", keywords: ["food", "dessert"] },
	{ char: "🎂", name: "birthday_cake", keywords: ["cake", "celebrate"] },
	{ char: "🍫", name: "chocolate", keywords: ["candy", "sweet"] },
	{ char: "🍿", name: "popcorn", keywords: ["movie", "snack"] },
	{ char: "🍺", name: "beer", keywords: ["drink", "alcohol"] },
	{ char: "🍷", name: "wine", keywords: ["drink", "alcohol"] },
	{ char: "🍸", name: "cocktail", keywords: ["drink", "martini"] },
	{ char: "🥤", name: "cup_straw", keywords: ["drink", "soda"] },
	{ char: "☕", name: "coffee", keywords: ["drink", "caffeine"] },
	{ char: "🍵", name: "tea", keywords: ["drink", "matcha"] },

	// Activities & sports
	{ char: "⚽", name: "soccer", keywords: ["football", "sport", "ball"] },
	{ char: "🏀", name: "basketball", keywords: ["sport", "ball"] },
	{ char: "🏈", name: "football", keywords: ["sport", "nfl"] },
	{ char: "⚾", name: "baseball", keywords: ["sport", "ball"] },
	{ char: "🎾", name: "tennis", keywords: ["sport", "ball"] },
	{ char: "🏐", name: "volleyball", keywords: ["sport", "ball"] },
	{ char: "🎱", name: "8ball", keywords: ["pool", "billiards"] },
	{ char: "🏓", name: "pingpong", keywords: ["table_tennis", "sport"] },
	{ char: "🎯", name: "dart", keywords: ["target", "bullseye"] },
	{ char: "🎲", name: "dice", keywords: ["game", "chance"] },
	{ char: "🎮", name: "video_game", keywords: ["controller", "gaming"] },
	{ char: "♟️", name: "chess", keywords: ["pawn", "game"] },
	{ char: "🎨", name: "art", keywords: ["paint", "palette", "design"] },
	{ char: "🎤", name: "microphone", keywords: ["sing", "karaoke", "podcast"] },
	{ char: "🎧", name: "headphones", keywords: ["music", "audio"] },
	{ char: "🎵", name: "musical_note", keywords: ["music", "sound"] },
	{ char: "🎶", name: "musical_notes", keywords: ["music", "song"] },
	{ char: "🎸", name: "guitar", keywords: ["music", "rock"] },
	{ char: "🥁", name: "drum", keywords: ["music", "beat"] },
	{ char: "🎬", name: "clapper", keywords: ["film", "movie"] },
	{ char: "📷", name: "camera", keywords: ["photo", "picture"] },
	{ char: "📸", name: "camera_flash", keywords: ["photo"] },
	{ char: "🎥", name: "video", keywords: ["film", "movie"] },
	{ char: "🏆", name: "trophy", keywords: ["winner", "award"] },
	{ char: "🥇", name: "first_place", keywords: ["gold", "medal", "winner"] },
	{ char: "🥈", name: "second_place", keywords: ["silver", "medal"] },
	{ char: "🥉", name: "third_place", keywords: ["bronze", "medal"] },
	{ char: "🎖️", name: "medal", keywords: ["military", "honor"] },

	// Travel & places
	{ char: "🚀", name: "rocket", keywords: ["space", "launch", "fast"] },
	{ char: "🛸", name: "ufo", keywords: ["alien", "saucer"] },
	{ char: "✈️", name: "airplane", keywords: ["travel", "flight"] },
	{ char: "🚗", name: "car", keywords: ["vehicle"] },
	{ char: "🚕", name: "taxi", keywords: ["cab", "vehicle"] },
	{ char: "🚙", name: "suv", keywords: ["car"] },
	{ char: "🚌", name: "bus", keywords: ["transport"] },
	{ char: "🚲", name: "bike", keywords: ["bicycle"] },
	{ char: "🛴", name: "scooter", keywords: ["kick", "transport"] },
	{ char: "🛹", name: "skateboard", keywords: ["board"] },
	{ char: "🚂", name: "train", keywords: ["rail", "locomotive"] },
	{ char: "🚇", name: "metro", keywords: ["subway", "underground"] },
	{ char: "🚢", name: "ship", keywords: ["boat", "cruise"] },
	{ char: "⛵", name: "sailboat", keywords: ["boat", "sea"] },
	{ char: "🛶", name: "canoe", keywords: ["boat"] },
	{ char: "🚦", name: "traffic_light", keywords: ["stop", "go"] },
	{ char: "🏠", name: "house", keywords: ["home", "building"] },
	{ char: "🏡", name: "home", keywords: ["house", "garden"] },
	{ char: "🏢", name: "office", keywords: ["building", "work"] },
	{ char: "🏥", name: "hospital", keywords: ["medical", "building"] },
	{ char: "🏫", name: "school", keywords: ["building", "education"] },
	{ char: "🏪", name: "store", keywords: ["shop", "convenience"] },
	{ char: "🏖️", name: "beach", keywords: ["sand", "umbrella", "vacation"] },
	{ char: "🏔️", name: "mountain", keywords: ["snow", "peak"] },
	{ char: "🗽", name: "statue_of_liberty", keywords: ["nyc", "usa"] },
	{ char: "🗼", name: "tokyo_tower", keywords: ["japan", "tower"] },
	{ char: "🌃", name: "night_city", keywords: ["skyline", "stars"] },

	// Objects, tools, tech
	{ char: "💡", name: "bulb", keywords: ["idea", "light", "lightbulb"] },
	{ char: "🔦", name: "flashlight", keywords: ["torch", "light"] },
	{ char: "🕯️", name: "candle", keywords: ["fire", "wax"] },
	{ char: "📱", name: "iphone", keywords: ["phone", "mobile"] },
	{ char: "💻", name: "laptop", keywords: ["computer", "mac"] },
	{ char: "🖥️", name: "desktop", keywords: ["computer", "monitor"] },
	{ char: "⌨️", name: "keyboard", keywords: ["typing", "computer"] },
	{ char: "🖱️", name: "mouse_three_button", keywords: ["computer"] },
	{ char: "🖨️", name: "printer", keywords: ["office"] },
	{ char: "💾", name: "floppy_disk", keywords: ["save", "storage"] },
	{ char: "💿", name: "cd", keywords: ["disc", "music"] },
	{ char: "📀", name: "dvd", keywords: ["disc", "video"] },
	{ char: "📡", name: "satellite", keywords: ["antenna", "signal"] },
	{ char: "🔋", name: "battery", keywords: ["power", "charge"] },
	{ char: "🔌", name: "plug", keywords: ["power", "electric"] },
	{ char: "🔍", name: "search", keywords: ["magnifying", "find", "zoom"] },
	{ char: "🔎", name: "search_right", keywords: ["magnifying", "find"] },
	{ char: "🔒", name: "lock", keywords: ["secure", "private"] },
	{ char: "🔓", name: "unlock", keywords: ["open"] },
	{ char: "🔑", name: "key", keywords: ["unlock", "access"] },
	{ char: "🗝️", name: "old_key", keywords: ["unlock"] },
	{ char: "🔨", name: "hammer", keywords: ["tool", "build"] },
	{ char: "🛠️", name: "tools", keywords: ["wrench", "fix", "build"] },
	{ char: "⚙️", name: "gear", keywords: ["settings", "cog"] },
	{ char: "🧲", name: "magnet", keywords: ["attract"] },
	{ char: "🧪", name: "test_tube", keywords: ["lab", "experiment"] },
	{ char: "🧬", name: "dna", keywords: ["science", "biology"] },
	{ char: "🔬", name: "microscope", keywords: ["science", "lab"] },
	{ char: "🔭", name: "telescope", keywords: ["astronomy", "space"] },
	{ char: "📚", name: "books", keywords: ["read", "library"] },
	{ char: "📖", name: "book", keywords: ["read", "open"] },
	{ char: "📓", name: "notebook", keywords: ["notes"] },
	{ char: "📝", name: "memo", keywords: ["note", "write", "pencil"] },
	{ char: "✏️", name: "pencil", keywords: ["write", "edit"] },
	{ char: "🖊️", name: "pen", keywords: ["write"] },
	{ char: "📅", name: "calendar", keywords: ["date", "schedule"] },
	{ char: "📌", name: "pushpin", keywords: ["pin", "save"] },
	{ char: "📎", name: "paperclip", keywords: ["attach", "office"] },
	{ char: "✂️", name: "scissors", keywords: ["cut"] },
	{ char: "💰", name: "moneybag", keywords: ["cash", "money"] },
	{ char: "💵", name: "dollar", keywords: ["money", "cash"] },
	{ char: "💳", name: "credit_card", keywords: ["payment", "money"] },
	{ char: "💎", name: "gem", keywords: ["diamond", "jewel"] },
	{ char: "🎁", name: "gift", keywords: ["present", "box"] },
	{ char: "🎈", name: "balloon", keywords: ["party", "celebrate"] },
	{ char: "🎉", name: "tada", keywords: ["party", "celebrate"] },
	{ char: "🎊", name: "confetti", keywords: ["party", "celebrate"] },
	{ char: "🏷️", name: "label", keywords: ["tag", "price"] },
	{ char: "💼", name: "briefcase", keywords: ["work", "business"] },
	{ char: "📦", name: "package", keywords: ["box", "shipping"] },
	{ char: "📤", name: "outbox", keywords: ["send"] },
	{ char: "📥", name: "inbox", keywords: ["receive"] },
	{ char: "📧", name: "email", keywords: ["mail", "envelope"] },
	{ char: "📨", name: "incoming_envelope", keywords: ["mail"] },
	{ char: "📬", name: "mailbox", keywords: ["mail", "post"] },
	{ char: "📢", name: "loudspeaker", keywords: ["announce", "shout"] },
	{ char: "📣", name: "megaphone", keywords: ["announce", "shout"] },
	{ char: "🔔", name: "bell", keywords: ["notification", "ring"] },
	{ char: "🛎️", name: "service_bell", keywords: ["hotel", "ding"] },
	{ char: "🗂️", name: "card_index_dividers", keywords: ["organize", "files"] },
	{ char: "📊", name: "bar_chart", keywords: ["graph", "stats"] },
	{ char: "📈", name: "chart_up", keywords: ["graph", "growth"] },
	{ char: "📉", name: "chart_down", keywords: ["graph", "decline"] },
	{ char: "💼", name: "portfolio", keywords: ["briefcase", "business"] },
	{ char: "🎯", name: "target", keywords: ["goal", "bullseye"] },

	// Symbols & marks
	{ char: "❤️", name: "heart", keywords: ["love", "red"] },
	{ char: "🧡", name: "orange_heart", keywords: ["love"] },
	{ char: "💛", name: "yellow_heart", keywords: ["love"] },
	{ char: "💚", name: "green_heart", keywords: ["love"] },
	{ char: "💙", name: "blue_heart", keywords: ["love"] },
	{ char: "💜", name: "purple_heart", keywords: ["love"] },
	{ char: "🖤", name: "black_heart", keywords: ["love", "dark"] },
	{ char: "🤍", name: "white_heart", keywords: ["love"] },
	{ char: "🤎", name: "brown_heart", keywords: ["love"] },
	{ char: "💔", name: "broken_heart", keywords: ["sad", "breakup"] },
	{ char: "❣️", name: "heart_exclamation", keywords: ["love"] },
	{ char: "💕", name: "two_hearts", keywords: ["love"] },
	{ char: "💖", name: "sparkling_heart", keywords: ["love"] },
	{ char: "✅", name: "check", keywords: ["done", "yes", "tick"] },
	{ char: "☑️", name: "ballot_box_check", keywords: ["check", "done"] },
	{ char: "✔️", name: "heavy_check_mark", keywords: ["done", "yes"] },
	{ char: "❌", name: "x", keywords: ["no", "cross", "wrong"] },
	{ char: "❎", name: "negative_squared_x", keywords: ["no"] },
	{ char: "⛔", name: "no_entry", keywords: ["stop", "forbidden"] },
	{ char: "🚫", name: "prohibited", keywords: ["no", "forbidden"] },
	{ char: "⚠️", name: "warning", keywords: ["caution", "alert"] },
	{ char: "🚨", name: "rotating_light", keywords: ["alert", "police"] },
	{ char: "❓", name: "question", keywords: ["help", "what"] },
	{ char: "❗", name: "exclamation", keywords: ["alert", "important"] },
	{ char: "💯", name: "100", keywords: ["perfect", "score"] },
	{ char: "♻️", name: "recycle", keywords: ["green", "environment"] },
	{ char: "🆕", name: "new", keywords: ["fresh"] },
	{ char: "🆓", name: "free", keywords: ["zero"] },
	{ char: "🆗", name: "ok", keywords: ["yes"] },
	{ char: "🆘", name: "sos", keywords: ["help", "emergency"] },
	{ char: "⏰", name: "alarm_clock", keywords: ["time", "wake"] },
	{ char: "⏱️", name: "stopwatch", keywords: ["time", "timer"] },
	{ char: "⌛", name: "hourglass_done", keywords: ["time", "wait"] },
	{ char: "⏳", name: "hourglass", keywords: ["time", "wait"] },
	{ char: "🕒", name: "three_oclock", keywords: ["time", "clock"] },
	{ char: "📍", name: "round_pushpin", keywords: ["pin", "location"] },
	{ char: "🗺️", name: "world_map", keywords: ["travel", "geo"] },
	{ char: "🧭", name: "compass", keywords: ["direction", "travel"] },
	{ char: "🏁", name: "checkered_flag", keywords: ["finish", "race"] },
	{ char: "🚩", name: "triangular_flag", keywords: ["flag", "milestone"] },
	{ char: "🏳️", name: "white_flag", keywords: ["surrender"] },
	{ char: "🏴", name: "black_flag", keywords: ["pirate"] },
	{ char: "🌐", name: "globe_meridians", keywords: ["world", "web", "internet"] },
	{ char: "♾️", name: "infinity", keywords: ["forever", "loop"] },
	{ char: "🆙", name: "up", keywords: ["arrow"] },
];

/** Lookup by short name (case-insensitive). */
const NAME_INDEX = new Map<string, EmojiEntry>(
	EMOJI_DATA.map((entry) => [entry.name.toLowerCase(), entry])
);

export function findEmojiByName(name: string): EmojiEntry | undefined {
	return NAME_INDEX.get(name.toLowerCase());
}

/**
 * Score-and-rank emoji search.
 *
 * Ranking:
 *   1. Exact name match — score 0
 *   2. Name starts with query — score 1
 *   3. Keyword starts with query — score 2
 *   4. Name contains query — score 3
 *   5. Keyword contains query — score 4
 *
 * Within the same score, sorted by name length (shorter first) for stability.
 */
export function searchEmojis(query: string, limit = 32): EmojiEntry[] {
	const q = query.trim().toLowerCase();
	if (!q) return [];

	const scored: { entry: EmojiEntry; score: number }[] = [];

	for (const entry of EMOJI_DATA) {
		const name = entry.name.toLowerCase();
		let score = -1;

		if (name === q) score = 0;
		else if (name.startsWith(q)) score = 1;
		else if (entry.keywords.some((k) => k.startsWith(q))) score = 2;
		else if (name.includes(q)) score = 3;
		else if (entry.keywords.some((k) => k.includes(q))) score = 4;

		if (score >= 0) scored.push({ entry, score });
	}

	scored.sort((a, b) => {
		if (a.score !== b.score) return a.score - b.score;
		return a.entry.name.length - b.entry.name.length;
	});

	return scored.slice(0, limit).map((s) => s.entry);
}
